apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-postgres
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-postgres
  template:
    metadata:
      labels:
        app: music-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: soundsphere-secrets
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: soundsphere-secrets
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: soundsphere-secrets
                key: POSTGRES_DB
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          hostPath:
            path: /mnt/data/music-postgres   # local node path
            type: DirectoryOrCreate
