# .pre-commit-config.yaml
repos:
  # Basic checks for line endings, large files, etc.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: detect-private-key

  # Python Code Formatter: Black
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  # Python Import Sorter: isort
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"] # Use black profile for compatibility

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: ["--in-place", "--remove-unused-variables", "--remove-all-unused-imports"]
