apiVersion: v1
kind: Secret
metadata:
  name: soundsphere-secrets
type: Opaque
stringData:
  DISCORD_API_KEY: "<YOUR_DISCORD_API_KEY>"
  LAVALINK_URI: "<YOUR_LAVALINK_URI>"
  LAVALINK_PASSWORD: "<YOUR_LAVALINK_PASSWORD>"
  POSTGRES_USER: "<YOUR_POSTGRES_USER>"
  POSTGRES_PASSWORD: "<YOUR_POSTGRES_PASSWORD>"
  POSTGRES_DB: "<YOUR_POSTGRES_DB>"
  POSTGRES_HOST: "<YOUR_POSTGRES_HOST>"
  POSTGRES_PORT: "5432"
  DATABASE_URL: "postgresql+psycopg2://<YOUR_POSTGRES_USER>:<YOUR_POSTGRES_PASSWORD>@<YOUR_POSTGRES_HOST>:5432/<YOUR_POSTGRES_DB>"
