"""Add server settings table

Revision ID: 728a2c4206d6
Revises: 7ea20660a0ab
Create Date: 2025-11-22 17:32:22.656112

"""

# revision identifiers, used by Alembic.
revision = "728a2c4206d6"
down_revision = "7ea20660a0ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
