"""init tables

Revision ID: 7ea20660a0ab
Revises: 
Create Date: 2025-11-21 22:28:00.295964

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7ea20660a0ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('play_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('track_title', sa.String(), nullable=True),
    sa.Column('track_author', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('played_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queue_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('track_title', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('track_author', sa.String(), nullable=True),
    sa.Column('added_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('requested_by', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queue_tracks')
    op.drop_table('play_history')
    # ### end Alembic commands ###
