"""Add track_number to album_tracks

Revision ID: ee6a9f868c5b
Revises: 728a2c4206d6
Create Date: 2025-11-22 22:45:47.094243

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ee6a9f868c5b"
down_revision = "728a2c4206d6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "album_tracks", sa.Column("track_number", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("album_tracks", "track_number")
    # ### end Alembic commands ###
