"""sync queue_tracks

Revision ID: fa386556ede0
Revises: 22922588cbe2
Create Date: 2025-11-25 02:14:04.918067

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fa386556ede0"
down_revision = "22922588cbe2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("album_tracks", sa.Column("identifier", sa.String(), nullable=True))
    op.add_column("play_history", sa.Column("identifier", sa.String(), nullable=True))
    op.add_column("queue_tracks", sa.Column("identifier", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("queue_tracks", "identifier")
    op.drop_column("play_history", "identifier")
    op.drop_column("album_tracks", "identifier")
    # ### end Alembic commands ###
