apiVersion: v1
kind: Service
metadata:
  name: soundsphere-bot
  namespace: dev
spec:
  selector:
    app: soundsphere-bot
  type: NodePort
  ports:
    - name: music-api
      protocol: TCP
      port: 8000
      targetPort: 5000
      nodePort: 30080
